# Generated by Django 2.2.6 on 2020-10-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200929_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aestheticsservice',
            old_name='model',
            new_name='master',
        ),
        migrations.RenameField(
            model_name='cosmetologyservice',
            old_name='model',
            new_name='master',
        ),
        migrations.RenameField(
            model_name='eyebrowservice',
            old_name='model',
            new_name='master',
        ),
        migrations.RenameField(
            model_name='hairremovalservice',
            old_name='model',
            new_name='master',
        ),
        migrations.RenameField(
            model_name='hairservice',
            old_name='model',
            new_name='master',
        ),
        migrations.RenameField(
            model_name='makeupservice',
            old_name='model',
            new_name='master',
        ),
        migrations.RenameField(
            model_name='massageservice',
            old_name='model',
            new_name='master',
        ),
        migrations.RenameField(
            model_name='nailsservice',
            old_name='model',
            new_name='master',
        ),
        migrations.RenameField(
            model_name='tattooservice',
            old_name='model',
            new_name='master',
        ),
    ]
