# Generated by Django 2.2.6 on 2020-05-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200530_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairremovalservice',
            name='promotion_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hairservice',
            name='promotion_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makeupservice',
            name='promotion_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='massageservice',
            name='promotion_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nailsservice',
            name='promotion_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
