# Generated by Django 2.2.6 on 2020-06-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200530_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairremovalservice',
            name='duration',
            field=models.IntegerField(blank=True, default=30),
        ),
        migrations.AddField(
            model_name='hairservice',
            name='duration',
            field=models.IntegerField(blank=True, default=30),
        ),
        migrations.AddField(
            model_name='makeupservice',
            name='duration',
            field=models.IntegerField(blank=True, default=30),
        ),
        migrations.AddField(
            model_name='massageservice',
            name='duration',
            field=models.IntegerField(blank=True, default=30),
        ),
        migrations.AddField(
            model_name='nailsservice',
            name='duration',
            field=models.IntegerField(blank=True, default=30),
        ),
    ]
