# Generated by Django 2.2.6 on 2020-08-28 21:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0012_auto_20200828_2101'),
        ('services', '0004_auto_20200605_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='TattooService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('promotion_price', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, default=30)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.Tattoo')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.Salon')),
            ],
        ),
        migrations.CreateModel(
            name='EyebrowService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('promotion_price', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, default=30)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.Eyebrow')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.Salon')),
            ],
        ),
        migrations.CreateModel(
            name='CosmetologyService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('promotion_price', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, default=30)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.Cosmetology')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.Salon')),
            ],
        ),
        migrations.CreateModel(
            name='AestheticsService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('promotion_price', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, default=30)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.Aesthetics')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.Salon')),
            ],
        ),
    ]
