# Generated by Django 2.2.6 on 2020-09-28 21:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_auto_20200929_0118'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='posted_by',
            new_name='voted_by',
        ),
        migrations.AddField(
            model_name='review',
            name='question1',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (2, 'Maybe'), (3, 'No'), (4, 'Skip')], default=4),
        ),
        migrations.AddField(
            model_name='review',
            name='question2',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (2, 'Maybe'), (3, 'No'), (4, 'Skip')], default=4),
        ),
        migrations.AddField(
            model_name='review',
            name='question3',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (2, 'Maybe'), (3, 'No'), (4, 'Skip')], default=4),
        ),
        migrations.AddField(
            model_name='review',
            name='question4',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (2, 'Maybe'), (3, 'No'), (4, 'Skip')], default=4),
        ),
        migrations.AddField(
            model_name='review',
            name='question5',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (2, 'Maybe'), (3, 'No'), (4, 'Skip')], default=4),
        ),
        migrations.AlterField(
            model_name='vote',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='is_useful',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.Salon')),
            ],
        ),
    ]
