# Generated by Django 2.2.6 on 2020-05-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='question1',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (2, 'Maybe'), (3, 'No'), (4, 'Skip')], default=4),
        ),
        migrations.AddField(
            model_name='review',
            name='question2',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (2, 'Maybe'), (3, 'No'), (4, 'Skip')], default=4),
        ),
        migrations.AddField(
            model_name='review',
            name='question3',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (2, 'Maybe'), (3, 'No'), (4, 'Skip')], default=4),
        ),
        migrations.AddField(
            model_name='review',
            name='question4',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (2, 'Maybe'), (3, 'No'), (4, 'Skip')], default=4),
        ),
        migrations.AddField(
            model_name='review',
            name='question5',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (2, 'Maybe'), (3, 'No'), (4, 'Skip')], default=4),
        ),
    ]
