# Generated by Django 2.2.6 on 2020-05-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200522_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='posted_by',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='voted_by',
        ),
    ]
