# Generated by Django 2.2.6 on 2020-05-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20200524_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='is_useful',
            field=models.BooleanField(default=False),
        ),
    ]
