# Generated by Django 2.2.6 on 2020-08-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_favorite',
        ),
    ]
