# Generated by Django 2.2.6 on 2020-09-28 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aesthetics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Aesthetics Categories',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('customer_mobile', models.CharField(blank=True, max_length=25, null=True)),
                ('service_title', models.CharField(blank=True, max_length=50)),
                ('service_price', models.PositiveIntegerField(blank=True, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cosmetology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cosmetology Categories',
            },
        ),
        migrations.CreateModel(
            name='Eyebrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Eyebrow Categories',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tattoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tattoo Categories',
            },
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='salon',
            name='appointment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salon',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salon',
            name='hair_categories',
            field=models.ManyToManyField(blank=True, to='salons.Hair'),
        ),
        migrations.AddField(
            model_name='salon',
            name='hair_removal_categories',
            field=models.ManyToManyField(blank=True, to='salons.HairRemoval'),
        ),
        migrations.AddField(
            model_name='salon',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salon',
            name='makeup_categories',
            field=models.ManyToManyField(blank=True, to='salons.Makeup'),
        ),
        migrations.AddField(
            model_name='salon',
            name='massage_categories',
            field=models.ManyToManyField(blank=True, to='salons.Massage'),
        ),
        migrations.AddField(
            model_name='salon',
            name='nails_categories',
            field=models.ManyToManyField(blank=True, to='salons.Nails'),
        ),
        migrations.AddField(
            model_name='salon',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salon',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salon',
            name='phone',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='salon',
            name='price_range',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '$'), (2, '$$'), (3, '$$$'), (4, '$$$$')]),
        ),
        migrations.AlterField(
            model_name='salon',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='master',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.Salon'),
        ),
        migrations.AddField(
            model_name='booking',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.Master'),
        ),
        migrations.AddField(
            model_name='salon',
            name='aesthetics_categories',
            field=models.ManyToManyField(blank=True, to='salons.Aesthetics'),
        ),
        migrations.AddField(
            model_name='salon',
            name='cosmetology_categories',
            field=models.ManyToManyField(blank=True, to='salons.Cosmetology'),
        ),
        migrations.AddField(
            model_name='salon',
            name='eyebrow_categories',
            field=models.ManyToManyField(blank=True, to='salons.Eyebrow'),
        ),
        migrations.AddField(
            model_name='salon',
            name='tattoo_categories',
            field=models.ManyToManyField(blank=True, to='salons.Tattoo'),
        ),
    ]
