# Generated by Django 2.2.6 on 2020-04-27 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salon',
            name='hair_categories',
            field=models.ManyToManyField(blank=True, to='salons.Hair'),
        ),
        migrations.AddField(
            model_name='salon',
            name='hair_removal_categories',
            field=models.ManyToManyField(blank=True, to='salons.HairRemoval'),
        ),
        migrations.AddField(
            model_name='salon',
            name='makeup_categories',
            field=models.ManyToManyField(blank=True, to='salons.Makeup'),
        ),
        migrations.AddField(
            model_name='salon',
            name='massage_categories',
            field=models.ManyToManyField(blank=True, to='salons.Massage'),
        ),
        migrations.AddField(
            model_name='salon',
            name='nails_categories',
            field=models.ManyToManyField(blank=True, to='salons.Nails'),
        ),
        migrations.AddField(
            model_name='like',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='salons.Salon'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
