# Generated by Django 2.2.6 on 2020-09-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_auto_20200929_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='name',
            new_name='master_name',
        ),
        migrations.RemoveField(
            model_name='master',
            name='email',
        ),
        migrations.RemoveField(
            model_name='master',
            name='phone',
        ),
        migrations.AddField(
            model_name='master',
            name='master_email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='master',
            name='master_phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
