# Generated by Django 2.2.6 on 2020-05-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_auto_20200427_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=5),
        ),
    ]
