# Generated by Django 2.2.6 on 2020-10-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_auto_20200930_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='home_visit',
            field=models.BooleanField(default=False),
        ),
    ]
