# Generated by Django 2.2.6 on 2020-11-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_master_home_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='freelancer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salon',
            name='outcall',
            field=models.BooleanField(default=False),
        ),
    ]
