# Generated by Django 2.2.6 on 2020-05-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_auto_20200508_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='photo_main',
            field=models.ImageField(upload_to='photos/%m/%d/%Y/'),
        ),
    ]
