# Generated by Django 2.2.6 on 2020-05-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_auto_20200508_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='photo_main',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
