# Generated by Django 2.2.6 on 2020-05-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0006_auto_20200508_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
