# Generated by Django 2.2.6 on 2020-08-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0007_auto_20200520_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
