# Generated by Django 2.2.6 on 2020-08-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0008_salon_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
