# Generated by Django 2.2.6 on 2021-01-07 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0010_auto_20210107_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salon',
            old_name='close',
            new_name='closing_hour',
        ),
        migrations.RenameField(
            model_name='salon',
            old_name='open',
            new_name='opening_hour',
        ),
    ]
