# Generated by Django 2.2.6 on 2020-08-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0010_salon_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
