# Generated by Django 2.2.6 on 2020-08-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0011_delete_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aesthetics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Aesthetics Categories',
            },
        ),
        migrations.CreateModel(
            name='Cosmetology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cosmetology Categories',
            },
        ),
        migrations.CreateModel(
            name='Eyebrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Eyebrow Categories',
            },
        ),
        migrations.CreateModel(
            name='Tattoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tattoo Categories',
            },
        ),
        migrations.AddField(
            model_name='salon',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salon',
            name='aesthetics_categories',
            field=models.ManyToManyField(blank=True, to='salons.Aesthetics'),
        ),
        migrations.AddField(
            model_name='salon',
            name='cosmetology_categories',
            field=models.ManyToManyField(blank=True, to='salons.Cosmetology'),
        ),
        migrations.AddField(
            model_name='salon',
            name='eyebrow_categories',
            field=models.ManyToManyField(blank=True, to='salons.Eyebrow'),
        ),
        migrations.AddField(
            model_name='salon',
            name='tattoo_categories',
            field=models.ManyToManyField(blank=True, to='salons.Tattoo'),
        ),
    ]
