# Generated by Django 2.2.6 on 2021-01-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0011_auto_20210108_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='facebook',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='instagram',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='page_view',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
