# Generated by Django 2.2.6 on 2020-09-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0012_auto_20200828_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='price_range',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '$'), (2, '$$'), (3, '$$$'), (4, '$$$$')]),
        ),
    ]
