# Generated by Django 2.2.6 on 2021-01-19 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0013_auto_20210119_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
