# Generated by Django 2.2.6 on 2021-01-19 10:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0014_auto_20210119_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 10, 5, 34, 719578, tzinfo=utc)),
        ),
    ]
