# Generated by Django 2.2.6 on 2021-01-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0016_auto_20210119_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='task_id',
        ),
    ]
