# Generated by Django 2.2.6 on 2021-01-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0019_booking_sms_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='message_id_customer',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='message_id_salon',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
