# Generated by Django 2.2.6 on 2021-01-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0020_auto_20210122_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='sms_limit',
            field=models.PositiveIntegerField(blank=True, default=10),
        ),
    ]
