# Generated by Django 2.2.6 on 2021-02-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0021_salon_sms_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='sms_limit',
        ),
    ]
