# Generated by Django 2.2.6 on 2021-02-09 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0022_remove_salon_sms_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='page_view',
        ),
    ]
