# Generated by Django 2.2.6 on 2021-02-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0025_auto_20210211_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='facebook',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='instagram',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
