# Generated by Django 2.2.6 on 2021-02-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0026_auto_20210211_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='salon',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
