# Generated by Django 2.2.6 on 2021-02-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0027_auto_20210211_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='instagram',
        ),
    ]
