# Generated by Django 2.2.6 on 2021-02-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0028_auto_20210211_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='facebook',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='salon',
            name='instagram',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
