# Generated by Django 2.2.6 on 2021-02-13 12:40

import django.contrib.postgres.fields
from django.db import migrations, models
import salons.models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0029_auto_20210211_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='friday_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=salons.models.Master.get_weekday_hours, size=2),
        ),
        migrations.AddField(
            model_name='master',
            name='monday_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=salons.models.Master.get_weekday_hours, size=2),
        ),
        migrations.AddField(
            model_name='master',
            name='saturday_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=salons.models.Master.get_weekend_hours, size=2),
        ),
        migrations.AddField(
            model_name='master',
            name='sunday_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=salons.models.Master.get_weekend_hours, size=2),
        ),
        migrations.AddField(
            model_name='master',
            name='thursday_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=salons.models.Master.get_weekday_hours, size=2),
        ),
        migrations.AddField(
            model_name='master',
            name='tuesday_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=salons.models.Master.get_weekday_hours, size=2),
        ),
        migrations.AddField(
            model_name='master',
            name='wednesday_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=salons.models.Master.get_weekday_hours, size=2),
        ),
    ]
