# Generated by Django 2.2.6 on 2020-04-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Visiter'), (2, 'Freelancer'), (3, 'SalonAdmin')], default=1),
        ),
    ]
